### DISCUSSION TITLE
[DOCKER] Sign multi-arch image

### DISCUSSION THREAD

**Discussion by Renizmy** [sigstore/cosign#4015] [Q&A]
Hello !

Based on this circle-ci step:

```
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build renizmy/python-client-container <<parameters.python_version>> <<parameters.tag>>
          command: |
            docker run --privileged --rm tonistiigi/binfmt --install linux/amd64,linux/arm64
            CIRCLE_TAG=${CIRCLE_TAG:-latest}
            docker buildx create --platform linux/amd64,linux/arm64 --use --name mybuilder 
            docker buildx inspect mybuilder --bootstrap
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker buildx build . \
              --platform linux/amd64,linux/arm64 \
              -t <<parameters.base_repo>>/client-python-<<parameters.python_version>>:${CIRCLE_TAG} \
              -t <<parameters.base_repo>>/client-python-<<parameters.python_version>>:latest \
              --build-arg BASE_IMAGE="<<parameters.base_image>>" \
              --cache-to=type=local,dest=client-python-<<parameters.python_version>>.tmp \
              --push
```

I'm trying to determine the proper output format for the docker buildx build command to sign a multi-arch image (including each sub-image) using cosign. However, it doesn't seem to work with each output (oci, tar, ..)

docker buildx build documentation: https://docs.docker.com/reference/cli/docker/buildx/build/#output

Does anyone have any suggestions?

Best regards,

**Comment by adilburaksen** [comment]
With cosign you sign the manifest list (image index) digest, not the per-platform images individually. The `docker buildx build` output format doesn't matter — what matters is capturing the digest of the manifest list after the push and signing that.

**Capture the digest with `--metadata-file`:**
```yaml
- run:
    name: Build and push multi-arch
    command: |
      docker buildx build .         --platform linux/amd64,linux/arm64         -t myrepo/myimage:${CIRCLE_TAG}         --push         --metadata-file /tmp/build-metadata.json
      
      # Extract the manifest list digest
      IMAGE_DIGEST=$(cat /tmp/build-metadata.json | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['containerimage.digest'])")
      echo "Manifest digest: $IMAGE_DIGEST"

- run:
    name: Sign with cosign
    command: |
      IMAGE_DIGEST=$(cat /tmp/build-metadata.json | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['containerimage.digest'])")
      cosign sign --key cosign.key         "myrepo/myimage@${IMAGE_DIGEST}"
```

The `containerimage.digest` field in the metadata file is the digest of the manifest list. Signing that digest signs the whole multi-arch image — any `cosign verify` against any platform tag will resolve back to the same manifest list digest.

**If `--metadata-file` isn't available (older buildx):** parse the digest from the `docker buildx imagetools inspect` output instead:
```sh
IMAGE_DIGEST=$(docker buildx imagetools inspect myrepo/myimage:${CIRCLE_TAG} --format '{{json .Manifest}}' | jq -r '.digest')
cosign sign --key cosign.key "myrepo/myimage@${IMAGE_DIGEST}"
```

No special output format (oci, tar) is needed — cosign works against the registry directly via the image reference with digest.
