### ISSUE TITLE
Signing complains about "invalid PEM block"

### ISSUE THREAD

**Issue by ckotzbauer** [sigstore/cosign#1051]
Hi all,

I'm playing around with cosign, Github Actions and GoReleaser. When I try to sign my artifacts via goreleaser and cosign I always get the error `Error: signing dist/mail-archiver_0.0.3_linux_arm64.tar.gz: reading key: invalid pem block artifact=mail-archiver_0.0.3_linux_arm64.tar.gz cmd=cosign`

**Versions**
- Cosign 1.3.1
- GoRelease 0.184.0

#### .goreleaser.yml
```yaml
signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    signature: "${artifact}.sig"
    args: ["sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}"]
    artifacts: all

```

#### Github Action
```yaml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.3.1'

      - name: Store cosign key
        run: echo "${COSIGN_KEY}" > cosign.key
        env:
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: "v0.184.0"
          args: release --rm-dist --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_EXPERIMENTAL: 1
          GORELEASER_CURRENT_TAG: ${{ github.event.inputs.version }}
```

The Public-Key is committed in the repo as `cosign.pub`, the Private-Key is available as `COSIGN_KEY` Github-Secret (without newlines - output of `cat cosign.key | tr -d '\n'` on linux).

Does anybody know what I'm doing wrong here? :smile: :see_no_evil: 
Thanks!!
