### ISSUE TITLE
random callback uri port

### ISSUE THREAD

**Issue by tuananh** [sigstore/cosign#1105]
the url generated is localhost:xxxxx . however the port is random each time so it doesn't match with what i have register in oidc idp (dex) and i get this error when the url opened in browser

```
Unregistered redirect_uri ("http://localhost:56947/auth/callback").
```

is there anyway to fix the port?

**Comment by tuananh** [comment]
@dlorenc i omit it so i assume it's the public dev one? the client i have registered in dex looks like below. 

```yaml
staticClients:
      - id: sigstore
        secret: __CHANGE_ME__
        name: 'sigstore'
        # Where the app will be running.
        redirectURIs:
        - 'http://localhost:56921/auth/callback'
        # - 'http://127.0.0.1:5555/callback'
```

as you can see, the redirect uri has port in it but everytime i run the below command, the port changed so i got `unregistered redirect_uri`

```
COSIGN_EXPERIMENTAL=1 cosign sign \
    --oidc-issuer "http://<my-dex-instance-url>" \
    README.md
```
