### ISSUE TITLE
Add support for reading image digests from a file

### ISSUE THREAD

**Issue by mattmoor** [sigstore/cosign#1219]
**Description**

Tools like `kaniko` have support for writing the published digest to a file to support results in systems like Tekton.

Signing these digests is awkward currently because you need to use shell functionality to read the result file:
```yaml
    - name: sign-result
      image: gcr.io/projectsigstore/cosign:v1.4.0
      env:
      - name: COSIGN_EXPERIMENTAL
        value: "1"
      command: [/busybox/sh, -c]
      args: ["/ko-app/cosign sign $(cat /tekton/results/IMAGES)"]
```

I propose adding support for reading these from a file.  A (straw-person) pattern for this would be to use `@filename`, which would shorten this to:
```yaml
    - name: sign-result
      image: gcr.io/projectsigstore/cosign:v1.4.0
      env:
      - name: COSIGN_EXPERIMENTAL
        value: "1"
      args: ["sign", "@/tekton/results/IMAGES"]
```
