### ISSUE TITLE
cosign generate-key-pair github://my-org/my-repo does not store the secrets accordingly in github

### ISSUE THREAD

**Issue by marcofranssen** [sigstore/cosign#1431]
**Description**

When generating a keypair like this the keys are not accordingly set in the GitHub secrets.

```shell
export GITHUB_TOKEN=my_token
$ cosign cosign generate-key-pair github://my-org/my-repo
Private key written to COSIGN_PASSWORD environment variable
Private key written to COSIGN_PRIVATE_KEY environment variable
Public key written to COSIGN_PUBLIC_KEY environment variable
Public key also written to cosign.pub
```

This is tested with following workflow.

```yaml
      - uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.5.1'

      - name: Cosign sign image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo '${{ secrets.COSIGN_PRIVATE_KEY }}' > cosign.key
          cosign sign --key cosign.key ghcr.io/my-org/hello-world:latest
```

This workflow results in printing the following in the logs.

```txt
echo '' > cosign.key
  cosign sign --key cosign.key ghcr.io/my-org/hello-world:latest
  shell: /usr/bin/bash -e {0}
  env:
    COSIGN_PASSWORD: 
an error occurred: no provider found for that key reference, will try to load key from disk...
```

> :warning: NOTE the empty echo statement in the first log line. as well the empty `COSIGN_PASSWORD` environment variable.

Also when trying to echo the generated keypairs from the shell where I ran the command `generate-keypair` it seems the environment variables are not set.

```shell
env | grep COSIGN_
echo $COSIGN_PUBLIC_KEY
echo $COSIGN_PRIVATE_KEY
echo $COSIGN_PASSWORD
```

However when generating key as following does show there is a secret.

```shell
cosign generate-key-pair
```

Then I simply update the secrets in Github by copy pasting the file contents.

When I run the workflow now it shows as following in the logs.

```txt
echo '***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ***
  ' > cosign.key
  cosign sign --key cosign.key ghcr.io/my-org/hello-world:latest
  shell: /usr/bin/bash -e {0}
  env:
    COSIGN_PASSWORD: ***
an error occurred: no provider found for that key reference, will try to load key from disk...
```

> :warning: Now the secrets are injected (redacted by Github). Both for the echo statement as well the env `COSIGN_PASSWORD`.

This might be caused by the version bump of the github package a while ago.
