### ISSUE TITLE
Oops. There's an extra level of indentation for authorities in ClusterImagePolicy

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#1592]
@mattmoor noticed that we actually had introduced an extra level of indentation for the authorities. It should be a sibling to images, but it's currently not.

From the examples here:
https://docs.google.com/document/d/1gBLEOOHWOmvHVsoJbgGU74GdwA6CGxMRp3MAeEB50l4/edit#

```
apiVersion: cosigned.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: image-policy
spec:
  images:
  - glob: *
  authorities:
```

But the way it's currently implemented it's inside images (from our valid test files):
```
apiVersion: cosigned.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: image-policy
spec:
  images:
  - glob: images.*
    authorities:
```
