### ISSUE TITLE
Ability to block admission if image SBOM contains specific package (defined in Cue)

### ISSUE THREAD

**Issue by jdolitsky** [sigstore/cosign#1954]
Currently, the policy admission controller is able to block admission based on the presence of certain attestations, evaluated against some Cue code. For example, from [here](https://github.com/sigstore/cosign/blob/main/test/testdata/policy-controller/e2e/cip-requires-two-signatures-and-two-attestations.yaml#L15):

```yaml
...
  policy:
    type: cue
    data: |
      package sigstore
      import "struct"
      import "list"
      authorityMatches: {
        keyatt: {
          attestations: struct.MaxFields(1) & struct.MinFields(1)
        },
...
```

I'd like the ability to, with similar syntax, prevent admission of a container with a SBOM that indicates it has a vulnerable package.

For example, the Log4Shell vulnerability ([CVE-2021-44228](https://nvd.nist.gov/vuln/detail/CVE-2021-44228)) affects several versions of the packages "log4j-api" and "log4j-core". Given that I have a attached an SBOM to my image, I'd like to be able to prevent admission based on whether a vulnerable version of one of these packages is listed in that SBOM.

Not sure what the inline Cue might look like, but something similar to `authorityMatches`, such as `packageMatches` where we can specify that specific versions of specific packages are not to be allowed.
