### ISSUE TITLE
Cosign, Spire, and Attestation failures

### ISSUE THREAD

**Issue by strongjz** [sigstore/cosign#1993]
Cosign attest should have flags for what identity is for signing attestation and another for the registry. 

If you use spire, cosign can not upload to the registry with the spire x509 SVID. It would be beneficial if we could instruct cosign explicitly via flag to use providers for specific tasks. 

Environment

Fulcio - helm chart version 0.3.0
Rekor - helm chart version 0.2.11
Tekton Pipelines - v0.2.3  
Tekton Chains - v0.8.0
Spire - `gcr.io/spiffe-io/spire-server@sha256:fbf64ed15687c1a5141b52d46d2b9082837fd286af16fbf670d155d0ec5e3dd3 #v1.2.0`
Cosign - `gcr.io/projectsigstore/cosign:v1.9.0`
GKE - 
``` k version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:36:49Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.900", GitCommit:"20da4c21b3a6b1a56ff6ad5ecb7dee013aaf1b83", GitTreeState:"clean", BuildDate:"2022-03-30T09:37:00Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

The tekton task uses the KSA and GSA that has access to GCR registry, this works fine. If we were to mount the Spire socket, the same KSA is registered with Spire, the GCR upload fails. 

```yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sbom-generate
spec:
  workspaces:
  params:
  - name: IMAGE
    type: string
    description: container image name
  - name: COSIGN_REPOSITORY
    type: string
    description: OCI repository for cosign to push sbom attestation too
    default: ""
  - name: SIGSTORE_CT_LOG_PUBLIC_KEY_FILE
    type: string
    default: ""
    description: |
      Cosign requires the ct log public key when interacting with private instances
      Setting this env variable will over ride what is used to validate the SCT coming back from Fulcio.
  - name: FULCIO_ENDPOINT
    type: string
    description: address of sigstore PKI server
  - name: REKOR_ENDPOINT
    type: string
    description: cosign defaults to using the public instance of rekor at rekor.sigstore.dev. To configure the rekor server

  steps:
  - name: trivy-sbom
    image: docker.io/aquasec/trivy:0.28.1
    command: ["trivy"]
    args: [
      "sbom",
      "--output", "/workspace/image.sbom",
      "--artifact-type", "image",
      "--sbom-format", "spdx",
      "$(params['IMAGE'])"
    ]
  - name: publish-sbom
    image: gcr.io/projectsigstore/cosign:v1.9.0
    timeout: 10m
    args: [
      "attest",
      # Use workload identity to access images
      "--k8s-keychain",
      # Disable timeout (registry http fallback takes more than the default)
      "--timeout=0",
      # Force the upload
      "--force",
      # Use the Rekor URL provided by the refresher.
      "--rekor-url", "$(params['REKOR_ENDPOINT'])",
      # Use the Fulcio URL provided by the refresher.
      "--fulcio-url", "$(params['FULCIO_ENDPOINT'])",
      # Use the "predicate" produced by the previous step.
      "--predicate", "/workspace/image.sbom",
      "$(params['IMAGE'])"
    ]
    env:
      - name: SIGSTORE_CT_LOG_PUBLIC_KEY_FILE
        value: $(params["SIGSTORE_CT_LOG_PUBLIC_KEY_FILE"])
      - name: COSIGN_EXPERIMENTAL
        value: "1"
      - name: COSIGN_REPOSITORY
        value: $(params["COSIGN_REPOSITORY"])
    volumeMounts:
    - name: oidc-info
      mountPath: /var/run/sigstore/cosign
    - name: ctlog-public-key
      mountPath: /data
  volumes:
  - name: oidc-info
    projected:
      sources:
        - serviceAccountToken:
            path: oidc-token
            expirationSeconds: 600 # Use as short-lived as possible.
            audience: sigstore
  - name: fulcio-cert
    secret:
      secretName: fulcio-secret
      items:
        - key: private
          path: key.pem
        - key: cert
          path: cert.pem
  - name: ctlog-public-key
    secret:
      items:
        - key: public
          path: ctlog-public.pem
      secretName: ctlog-public-key
      # This is marked as optional so that we can use with public Fulcio as
      # well by not specifying SIGSTORE_CT_LOG_PUBLIC_KEY_FILE.
      optional: true
```

Failure with Spire, Spire SVID works, with signing, but the upload fails. 

```
[sbom : publish-sbom] Generating ephemeral keys...
[sbom : publish-sbom] Retrieving signed certificate...
[sbom : publish-sbom] 
[sbom : publish-sbom]         Note that there may be personally identifiable information associated with this signed artifact.
[sbom : publish-sbom]         This may include the email address associated with the account with which you authenticate.
[sbom : publish-sbom]         This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later.
[sbom : publish-sbom] **Warning** Using a non-standard public key for verifying SCT: /data/ctlog-public.pem
[sbom : publish-sbom] Successfully verified SCT...
[sbom : publish-sbom] Using payload from: /workspace/image.sbom
[sbom : publish-sbom] tlog entry created with index: 526
[sbom : publish-sbom] Error: signing gcr.io/$IMAGE_NAME@sha256:3210065ee0eacc21e639bc96a237101bf6964672ffdacd4b7319d89e5ff6a9c4: GET https://gcr.io/v2/$IMAGE_NAME/manifests/sha256:3210065ee0eacc21e639bc96a237101bf6964672ffdacd4b7319d89e5ff6a9c4: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
[sbom : publish-sbom] main.go:52: error during command execution: signing gcr.io/$IMAGE_NAME@sha256:3210065ee0eacc21e639bc96a237101bf6964672ffdacd4b7319d89e5ff6a9c4: GET https://gcr.io/v2/$IMAGE_NAME/manifests/sha256:3210065ee0eacc21e639bc96a237101bf6964672ffdacd4b7319d89e5ff6a9c4: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication

failed to get logs for task sbom : container step-publish-sbom has failed  : [{"key":"StartedAt","value":"2022-06-09T21:51:37.413Z","type":3}]
Tasks Completed: 6 (Failed: 2, Cancelled 0), Skipped: 0
$ rekor-cli get --log-index 526 --rekor_server $REKOR_URL --format json | jq -r .Body.IntotoObj.publicKey| base64 -d | openssl x509 -noout -text -extensions subjectAltName | grep "Subject Alternative Name" -A3
            X509v3 Subject Alternative Name: critical
                URI:spiffe://$SPIREDOMAIN/ns/default/sa/tekton-sa
            1.3.6.1.4.1.57264.1.1: 
                https://$SPIREDOMAIN/
```
