### ISSUE TITLE
Cosigned - Webhook are not trigger even if the namespace is correctly labeled

### ISSUE THREAD

**Issue by quadrinho** [sigstore/cosign#2433]
**Version**
App Version 1.8.0
Chart Version 0.1.23

**Description**

I have tried to deploy the last version of the cosigned chart and the pod are up&running but i see in the logs:

```
{"level":"info","ts":"2022-11-09T16:56:43.425Z","logger":"cosigned.DefaultingWebhook","caller":"controller/controller.go:550","msg":"Reconcile succeeded","commit":"9ef6b20","knative.dev/traceid":"8806c857-4187-45ae-9dac-c02459695500","knative.dev/key":"argocd/webhook-certs","duration":0.090687279}
{"level":"error","ts":"2022-11-09T16:56:43.432Z","logger":"cosigned.ValidationWebhook","caller":"controller/controller.go:566","msg":"Reconcile error","commit":"9ef6b20","knative.dev/traceid":"e2d47e24-3bdf-47e1-ac61-60bba46e58e1","knative.dev/key":"cosigned.sigstore.vdf","duration":0.091272538,"error":"failed to update webhook: Operation cannot be fulfilled on validatingwebhookconfigurations.admissionregistration.k8s.io \"cosigned.sigstore.vdf\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20220325200448-1f7514acd0c2/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220325200448-1f7514acd0c2/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220325200448-1f7514acd0c2/controller/controller.go:491"}
{"level":"error","ts":"2022-11-09T16:56:43.509Z","logger":"cosigned.DefaultingWebhook","caller":"controller/controller.go:566","msg":"Reconcile error","commit":"9ef6b20","knative.dev/traceid":"b8f7599f-00f8-4103-bf0f-08eb313f6d19","knative.dev/key":"cosigned.sigstore.vdf","duration":0.168674564,"error":"failed to update webhook: Operation cannot be fulfilled on mutatingwebhookconfigurations.admissionregistration.k8s.io \"cosigned.sigstore.vdf\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20220325200448-1f7514acd0c2/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220325200448-1f7514acd0c2/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220325200448-1f7514acd0c2/controller/controller.go:491"}
{"level":"info","ts":"2022-11-09T16:56:43.517Z","logger":"cosigned.ValidationWebhook","caller":"validation/reconcile_config.go:173","msg":"Updating webhook","commit":"9ef6b20","knative.dev/traceid":"bbad1e4a-a0d8-4102-abfa-2df856fe1a16","knative.dev/key":"cosigned.sigstore.vdf"}
{"level":"info","ts":"2022-11-09T16:56:43.611Z","logger":"cosigned.DefaultingWebhook","caller":"defaulting/defaulting.go:253","msg":"Updating webhook","commit":"9ef6b20","knative.dev/traceid":"ff81aac0-f467-4175-b483-52ea2edc8ed3","knative.dev/key":"cosigned.sigstore.vdf"}
{"level":"info","ts":"2022-11-09T16:56:43.612Z","logger":"cosigned.ValidationWebhook","caller":"controller/controller.go:550","msg":"Reconcile succeeded","commit":"9ef6b20","knative.dev/traceid":"bbad1e4a-a0d8-4102-abfa-2df856fe1a16","knative.dev/key":"cosigned.sigstore.vdf","duration":0.179883746}
{"level":"info","ts":"2022-11-09T16:56:43.713Z","logger":"cosigned.ValidationWebhook","caller":"validation/reconcile_config.go:173","msg":"Updating webhook","commit":"9ef6b20","knative.dev/traceid":"18a641ae-b226-4747-b385-126683c79f89","knative.dev/key":"cosigned.sigstore.vdf"}
{"level":"info","ts":"2022-11-09T16:56:43.713Z","logger":"cosigned.DefaultingWebhook","caller":"controller/controller.go:550","msg":"Reconcile succeeded","commit":"9ef6b20","knative.dev/traceid":"ff81aac0-f467-4175-b483-52ea2edc8ed3","knative.dev/key":"cosigned.sigstore.vdf","duration":0.204078579}
{"level":"info","ts":"2022-11-09T16:56:43.809Z","logger":"cosigned.DefaultingWebhook","caller":"defaulting/defaulting.go:253","msg":"Updating webhook","commit":"9ef6b20","knative.dev/traceid":"f99054cc-1f4b-4564-97e7-1adb63cdcb4e","knative.dev/key":"cosigned.sigstore.vdf"}
{"level":"info","ts":"2022-11-09T16:56:43.810Z","logger":"cosigned.ValidationWebhook","caller":"controller/controller.go:550","msg":"Reconcile succeeded","commit":"9ef6b20","knative.dev/traceid":"18a641ae-b226-4747-b385-126683c79f89","knative.dev/key":"cosigned.sigstore.vdf","duration":0.198162737}
{"level":"info","ts":"2022-11-09T16:56:43.817Z","logger":"cosigned.DefaultingWebhook","caller":"controller/controller.go:550","msg":"Reconcile succeeded","commit":"9ef6b20","knative.dev/traceid":"f99054cc-1f4b-4564-97e7-1adb63cdcb4e","knative.dev/key":"cosigned.sigstore.vdf","duration":0.104080899}
```

I also tried to create a namespace and label it and install it the nginx chart:

```
kubectl label namespace test cosigned.sigstore.vdf/include="true"

helm install my-ingress-nginx ingress-nginx/ingress-nginx --version 4.3.0 -n test
```

The chart is installed and the webhooks are not triggered.

Below the values.yaml used to install cosigned chart:

```
cosign:
  secretKeyRef:
    name: "cosign-kms-pub"
    #name: "mysecret"
  # add the values in base64 encoded
  cosignPub: ""
  webhookName: "cosigned.sigstore.vdf"

policywebhook:
  image:
    repository: myregistry/projectsigstore/policy-webhook
    #version: sha256:5eee36d3e0a7b2ebd92da9cff183e77dd3e9e9e33d94cbe9bc171d084135158a
    version: 1.0.0
    pullPolicy: IfNotPresent
  env: {}
  extraArgs: {}
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  serviceAccount:
    annotations: {}
  securityContext:
    enabled: false
    runAsUser: 65532
  podSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
        - all
  service:
    annotations: {}
    type: ClusterIP
    port: 443
  webhookNames:
    defaulting: "defaulting.clusterimagepolicy.sigstore.vdf"
    validating: "validating.clusterimagepolicy.sigstore.vdf"

webhook:
  name: webhook
  image:
    repository: myregistry/projectsigstore/cosigned
    #version: sha256:784518ff3ee755ce42e174e61036094af771c43bdc76b65a8f0e52481ed450ac
    version: 1.0.0
    pullPolicy: IfNotPresent
  env: {}
  extraArgs: {}
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    enabled: false
    runAsUser: 65532
  podSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsUser: 1000
    capabilities:
      drop:
        - all
  serviceAccount:
    annotations: {}
  service:
    annotations: {}
    type: ClusterIP
    port: 443
    # For nodeport, specify the following:
    #   type: NodePort
    #   nodePort: <port-number>

## common node selector for all the pods
commonNodeSelector: {}
#  key1: value1
#  key2: value2

## common tolerations for all the pods
commonTolerations: []
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"

## serviceMonitor makes cosigned metrics discoverable to prometheus
serviceMonitor:
  enabled: false
```

Can you (or someone) help to understand which is the issue?

Thanks a lot!
