### ISSUE TITLE
Github Action step  Sign the published Docker image  returned 504 Gateway Timeout

### ISSUE THREAD

**Issue by zctmdc** [sigstore/cosign#2507]
**Description**

```bash
main.go:62: error during command execution: 
  signing [docker.io/***/mariadb:latest@sha256:6978cac3f15b020ee8d5a2907dab3bba0fc10f5fdb01acf351eb89e6e6add1f0]: 
  getting signer: getting key from Fulcio: retrieving cert: 
  POST https://fulcio.sigstore.dev/api/v1/signingCert returned 504 Gateway Timeout: 
```
<pre>
<code>
"<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
</code>
</pre>

**Version**

```yaml
      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: "v1.13.1"
```

<https://github.com/zctmdc/mariadb-galera-jagerzhang/blob/master/.github/workflows/docker-publish.yml>
