### ISSUE TITLE
cosign is not working with Gitlab self hosted 

### ISSUE THREAD

**Issue by pcsgithubid** [sigstore/cosign#2730]
I am trying to sign and push images to GitLab self-hosted environment using the below command, but the signing process trying to get project info using  gitlab.com API instead of  GitLab self-hosted API.

 cosign generate-key-pair gitlab://373
Enter password for private key:Enter password for private key again:
Error: could not create "COSIGN_PASSWORD" variable: POST https://gitlab.com/api/v4/projects/373/variables: 401 {message: 401 Unauthorized}
main.go:52: error during command execution: could not create "COSIGN_PASSWORD" variable: POST https://gitlab.com/api/v4/projects/373/variables: 401 {message: 401 Unauthorized}

how to work with self-hosted GitLab environments, please provide info

**Comment by cpanato** [comment]
you need to set the following environment variables and then you can run the cosign command

```
export GITLAB_TOKEN=<YOUR_TOKEN>
export GITLAB_HOST=<YOUR_GITLAB_HOST>

cosign generate-key-pair gitlab://<YOUR_PROJECT_ID>
```

**Comment by pcsgithubid** [comment]
That works. Thanks for the information.

**Comment by znewman01** [comment]
It wouldn't be a terrible idea to suggest this as a fix when we see that error.

**Comment by paolomainardi** [comment]
Hi :) if this one is still available, it seems a very small one to start contributing the project :)

**Comment by znewman01** [comment]
Thanks @paolomainardi ! Let me know if you're running into any trouble or have any questions.

**Comment by paolomainardi** [comment]
Wow, thanks @znewman01, I’ll get back to you with some questions and hopefully a PR very soon :)

**Comment by paolomainardi** [comment]
@znewman01 not very sure about the text and the format I should use and neither if there are tests for these files, asking you for a quick review.

**Comment by manuschillerdev** [comment]
I'd also be interested in a full example for a private gitlab instance.

> you need to set the following environment variables and then you can run the cosign command
> 
> ```
> export GITLAB_TOKEN=<YOUR_TOKEN>
> export GITLAB_HOST=<YOUR_GITLAB_HOST>
> 

`GITLAB_HOST` should be equal to `$CI_SERVER_HOST:$CI_SERVER_PORT`, right?
What would the GITLAB_TOKEN be? Which scopes should be allowed?

As a starting point for discussion: a basic pipeline that builds an image and tries to sign it:

```yaml
variables:
  DOCKER_AUTH_CONFIG: '{"auths": {"$DOCKER_REGISTRY_URL": {"auth": "$DOCKER_REGISTRY_AUTH_CONFIG"}}}'
  IMAGE_DESTINATION: "$DOCKER_REGISTRY_URL/$CI_PROJECT_PATH"

stages:
  - oci

oci:build:
  stage: oci
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "${DOCKER_AUTH_CONFIG}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --cleanup
      --cache
      --cache-repo "IMAGE_DESTINATION_cache"
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination "$IMAGE_DESTINATION:$CI_COMMIT_SHORT_SHA"

oci:sign:
  stage: oci
  image: "bitnami/cosign:latest"
  variables:
    - GITLAB_HOST: "$CI_SERVER_HOST:$CI_SERVER_PORT"
    - GITLAB_TOKEN: "?"
  # script: 
  #   - get sha265 of created image -> IMAGE_SHA_256
  #   - cosign sign -key ? $IMAGE_DESTINATION:$IMAGE_SHA_256
```
Can someone help me fill the gaps? I am unsure about how to create the keypair that should be stored as Gitlab-CI Env Variables, and about the detailed job configuration.

Thanks a lot!
