### ISSUE TITLE
"cosign dockerfile verify" fails with "file name too long" error in CircleCI

### ISSUE THREAD

**Issue by dneville-cvs** [sigstore/cosign#2803]
**Description**

In CircleCI, `cosign dockerfile verify` runs into a `main.go:74: error during command execution: loading public key: open **<< 95 characters removed >>**: file name too long` error.

**Minimal CircleCI config to reproduce error**
```yaml
---
version: 2.1

parameters:
  machine:
    type: string
    default: "ubuntu-2204:2022.10.2"

env-context: &env-context cci-global

jobs:
  cosign-bug:
    machine:
      image: << pipeline.parameters.machine >>
    parameters:
      registry_url:
        default: "https://us-east1-docker.pkg.dev"
        description: Container registry URL
        type: string
      registry_username:
        default: "_json_key_base64"
        description: Container registry username
        type: string
      registry_password:
        default: GCR_KEY
        description: Container registry username
        type: env_var_name
      certificate-identity:
        default: keyless@distroless.iam.gserviceaccount.com
        description: Certificate email
        type: string
      certificate-oidc-issuer:
        default: https://accounts.google.com
        description: OIDC issuer for the cert
        type: string
    steps:
      - run:
          name: Create Dockerfile
          command: |
            echo "FROM gcr.io/distroless/python3-debian11:nonroot" > Dockerfile
            echo "CMD [\"echo\", \"fubar\"]" >> Dockerfile
      - run:
          name: Set up GCP SAK
          command: |
            echo ${<< parameters.registry_password >>} | base64 -d > gcp_sak.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS="$HOME/project/gcp_sak.json"' >> "$BASH_ENV"
      - run:
          name: Download cosign
          command: |
              curl -OL https://github.com/sigstore/cosign/releases/download/v2.0.0/cosign-linux-amd64
              sudo mv cosign-linux-amd64 /usr/local/bin/cosign
              sudo chmod +x /usr/local/bin/cosign
      - run:
          name: Verify Dockerfile Base Image
          command: |
            cosign dockerfile verify --insecure-ignore-tlog=true --base-image-only --certificate-identity << parameters.certificate-identity >> --certificate-oidc-issuer << parameters.certificate-oidc-issuer >> ./Dockerfile

workflows:
  on-merge:
    jobs:
      - cosign-bug:
          name: cosign-bug
          context: *env-context

```

**Expected**
```
➜  cosign-sandbox git:(master) echo "FROM gcr.io/distroless/python3-debian11:nonroot\nRUN echo fubar" > Dockerfile
➜  cosign-sandbox git:(master) ✗ cosign dockerfile verify --insecure-ignore-tlog=true --base-image-only --certificate-identity keyless@distroless.iam.gserviceaccount.com --certificate-oidc-issuer https://accounts.google.com ./Dockerfile
Extracted image(s): gcr.io/distroless/python3-debian11:nonroot

Verification for gcr.io/distroless/python3-debian11:nonroot --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The code-signing certificate was verified using trusted certificate authority certificates

[{"critical":{"identity":{"docker-reference":"gcr.io/distroless/python3-debian11"},"image":{"docker-manifest-digest":"sha256:3b4307993ae073a8786b8e85855b6c224def928f275758500db005507dea1f3e"},"type":"cosign container image signature"},"optional":{"1.3.6.1.4.1.57264.1.1":"https://accounts.google.com","Bundle":{"SignedEntryTimestamp":"MEUCID37z3wIahjOFX8k57BklqRqbfs1oqCMyvb4LNsnxtmhAiEA0zC6Vio44ycq9q8y2F9JLCb0thj+nbB9Ls0yCfa5USY=","Payload":{"body":"eyJhcGlWZXJzaW9uIjoiMC4wLjEiLCJraW5kIjoiaGFzaGVkcmVrb3JkIiwic3BlYyI6eyJkYXRhIjp7Imhhc2giOnsiYWxnb3JpdGhtIjoic2hhMjU2IiwidmFsdWUiOiI0YjNmZWE2N2IxMWRhMzUyOWVjZTVkYWYxY2VjMjk4MmYzMTg4NmZlYTU3NmUwY2JlYjA0MDczNzA0YmY0MWU4In19LCJzaWduYXR1cmUiOnsiY29udGVudCI6Ik1FUUNJQzZXSmxmRW9kdE4rckpkdFRucTJOWGw0Sm1yenE1UVpuZytlS1gwU3Rib0FpQWNHUm5sUW9NRXZHeVl4K0xOaTg0SXNnTzRkTzVFNUxDN1I4aG9laEl0eWc9PSIsInB1YmxpY0tleSI6eyJjb250ZW50IjoiTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVTjBla05EUVdwNVowRjNTVUpCWjBsVlRqQjNVVFkyTUdKSWFEWjRhWGM1YzJScE1ITTNhMnhFV0c1QmQwTm5XVWxMYjFwSmVtb3dSVUYzVFhjS1RucEZWazFDVFVkQk1WVkZRMmhOVFdNeWJHNWpNMUoyWTIxVmRWcEhWakpOVWpSM1NFRlpSRlpSVVVSRmVGWjZZVmRrZW1SSE9YbGFVekZ3WW01U2JBcGpiVEZzV2tkc2FHUkhWWGRJYUdOT1RXcE5kMDE2UlhwTlZGVjZUbXBOTTFkb1kwNU5hazEzVFhwRmVrMVVWVEJPYWswelYycEJRVTFHYTNkRmQxbElDa3R2V2tsNmFqQkRRVkZaU1V0dldrbDZhakJFUVZGalJGRm5RVVV2VFdrMVFsSmFWMnhZYlRWVVMxb3hNQ3R3YmpabllsRk9XbUp4WlN0aGExcFVSQzhLUjNKVlpWTmFlVmRyYVVwalFsRXJTbVF2ZDJvellpdFFhWFozVUhFMlprZENSVXRNVEVObFdHNWpWeXRMV0RGdlUzRlBRMEZXYzNkblowWllUVUUwUndwQk1WVmtSSGRGUWk5M1VVVkJkMGxJWjBSQlZFSm5UbFpJVTFWRlJFUkJTMEpuWjNKQ1owVkdRbEZqUkVGNlFXUkNaMDVXU0ZFMFJVWm5VVlZET0cxS0NrTmlSRnB0TmxSb00zQlRWbkFyYkZSYWNUVnpja1JGZDBoM1dVUldVakJxUWtKbmQwWnZRVlV6T1ZCd2VqRlphMFZhWWpWeFRtcHdTMFpYYVhocE5Ga0tXa1E0ZDA5QldVUldVakJTUVZGSUwwSkROSGRNU1VWeFlUSldOV0pIVm5wak1FSnJZVmhPTUdOdE9YTmFXRTU2VEcxc2FHSlROVzVqTWxaNVpHMXNhZ3BhVjBacVdUSTVNV0p1VVhWWk1qbDBUVU5yUjBOcGMwZEJVVkZDWnpjNGQwRlJSVVZITW1nd1pFaENlazlwT0haWlYwNXFZak5XZFdSSVRYVmFNamwyQ2xveWVHeE1iVTUyWWxSRFFtbG5XVXRMZDFsQ1FrRklWMlZSU1VWQloxSTRRa2h2UVdWQlFqSkJUakE1VFVkeVIzaDRSWGxaZUd0bFNFcHNiazUzUzJrS1UydzJORE5xZVhRdk5HVkxZMjlCZGt0bE5rOUJRVUZDYUhSMVpIcElZMEZCUVZGRVFVVmpkMUpSU1dka1oxQk5XVlJpTm5WWmVVaHpabEpSV25FMFFncEphVGxWY1VwMlZXMXJZM2hNVDBwTU1tNHJWVzF5TUVOSlVVUmpjRXBJY0hVcmF6TmpXQ3QwWmxGblZGQnpVa3BJZVUxU2MwbHNOMDlaZVRBM1NGQXlDbGczVHpFM1JFRkxRbWRuY1docmFrOVFVVkZFUVhkT2NFRkVRbTFCYWtWQmVXVnhPR0V3YUdKbVNVMXpiaXN6ZG5kVFZWZGhZVWcwT1dFMmVWRnBkbWtLS3pCbmJUVjBObWQyYjNnelNFSndVVFZvVmpCcGVETkVjSGRxVURKWk9XdEJha1ZCZDJkU1ZHWnBNMWhtT1ZnMVFrMTNUMjU0UjNWM1pGQlRORUppTVFwbGVWQndjbEZQTVRsQlV6RjVXRTlzZGpabWQzaGlWMUl6YkVWRmJVODRkME5OU2xNS0xTMHRMUzFGVGtRZ1EwVlNWRWxHU1VOQlZFVXRMUzB0TFFvPSJ9fX19","integratedTime":1678721797,"logIndex":15328996,"logID":"c0d23d6ad406973f9559f3ba2d1ca01f84147d8ffc5b8445c224f98b9591801d"}},"Issuer":"https://accounts.google.com","Subject":"keyless@distroless.iam.gserviceaccount.com"}},{"critical":{"identity":{"docker-reference":"gcr.io/distroless/python3-debian11"},"image":{"docker-manifest-digest":"sha256:3b4307993ae073a8786b8e85855b6c224def928f275758500db005507dea1f3e"},"type":"cosign container image signature"},"optional":{"1.3.6.1.4.1.57264.1.1":"https://accounts.google.com","Bundle":{"SignedEntryTimestamp":"MEYCIQDWT9Ol1u8S4cxBEO3L4Oh/3M2t9oNU7w08jnPStz6xNwIhAJSSzVB4Z5Vrc6JqS5UNUFh34l1NxNpELJwtFmJg0JYn","Payload":{"body":"eyJhcGlWZXJzaW9uIjoiMC4wLjEiLCJraW5kIjoiaGFzaGVkcmVrb3JkIiwic3BlYyI6eyJkYXRhIjp7Imhhc2giOnsiYWxnb3JpdGhtIjoic2hhMjU2IiwidmFsdWUiOiI0YjNmZWE2N2IxMWRhMzUyOWVjZTVkYWYxY2VjMjk4MmYzMTg4NmZlYTU3NmUwY2JlYjA0MDczNzA0YmY0MWU4In19LCJzaWduYXR1cmUiOnsiY29udGVudCI6Ik1FWUNJUURzWWtuYWRUa3pnT1ZHbkVpd0k2eTljWTBJb2ZyYitUL0owTmYxeHE0N2hnSWhBUGJ0eXNlUEwvZ3VtMFNMUktjZmJXbjdlQmlTMVFHNDEwWlNNa2dwcXh6NSIsInB1YmxpY0tleSI6eyJjb250ZW50IjoiTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVTjBha05EUVdwNVowRjNTVUpCWjBsVlZrUmFZVGxxVEVaTFRtYzRNMVY0V0hkQlJucE9hWGRpYVZrNGQwTm5XVWxMYjFwSmVtb3dSVUYzVFhjS1RucEZWazFDVFVkQk1WVkZRMmhOVFdNeWJHNWpNMUoyWTIxVmRWcEhWakpOVWpSM1NFRlpSRlpSVVVSRmVGWjZZVmRrZW1SSE9YbGFVekZ3WW01U2JBcGpiVEZzV2tkc2FHUkhWWGRJYUdOT1RXcE5kMDE2UlhwTlZHTXhUbnBSTTFkb1kwNU5hazEzVFhwRmVrMVVaM2RPZWxFelYycEJRVTFHYTNkRmQxbElDa3R2V2tsNmFqQkRRVkZaU1V0dldrbDZhakJFUVZGalJGRm5RVVV4TjNSWFJrNDNSbkpVSzFOM1Z6ZG1SMXBDTnk5bkswcHliekZKUTIwNVpGRkVlRGdLV0RGS2J6aGxTM28xUzNacFR6VmtNWGxYSzBsT2VsTXZZa2N3U1hBMlpFUTBXRnBRZVdwRmVXSk1NMWRUVkdSRWFrdFBRMEZXYzNkblowWllUVUUwUndwQk1WVmtSSGRGUWk5M1VVVkJkMGxJWjBSQlZFSm5UbFpJVTFWRlJFUkJTMEpuWjNKQ1owVkdRbEZqUkVGNlFXUkNaMDVXU0ZFMFJVWm5VVlZLTjBsR0NuTTRhVWhSVVZVeVRraEtkMDlpTTFabU1rMUljUzlaZDBoM1dVUldVakJxUWtKbmQwWnZRVlV6T1ZCd2VqRlphMFZhWWpWeFRtcHdTMFpYYVhocE5Ga0tXa1E0ZDA5QldVUldVakJTUVZGSUwwSkROSGRNU1VWeFlUSldOV0pIVm5wak1FSnJZVmhPTUdOdE9YTmFXRTU2VEcxc2FHSlROVzVqTWxaNVpHMXNhZ3BhVjBacVdUSTVNV0p1VVhWWk1qbDBUVU5yUjBOcGMwZEJVVkZDWnpjNGQwRlJSVVZITW1nd1pFaENlazlwT0haWlYwNXFZak5XZFdSSVRYVmFNamwyQ2xveWVHeE1iVTUyWWxSRFFtbG5XVXRMZDFsQ1FrRklWMlZSU1VWQloxSTRRa2h2UVdWQlFqSkJUakE1VFVkeVIzaDRSWGxaZUd0bFNFcHNiazUzUzJrS1UydzJORE5xZVhRdk5HVkxZMjlCZGt0bE5rOUJRVUZDYUhSM1prTTFkMEZCUVZGRVFVVmpkMUpSU1doQlNrOW1hRzluTHpKTmMwbEVjSEF3UkU5akx3cHdPVWswTVc5VVZXRXpkekpYY0hsM05sSnpOMlJIVWt0QmFVSkhTRTVrWmxsSmEzZEZLMHBqUXpFd1YxbG5RVzV4WVVWTWJYWkxVMFV4TkhNM1ltUTFDakpaY1ZGeWVrRkxRbWRuY1docmFrOVFVVkZFUVhkT2IwRkVRbXhCYWtWQkwwTnJSRWRXS3pRdlF6QkpiVGd6Y21oSVkzcHdNSFZWVVV0U1J6TkljMUlLUmpOdmJHeFZZazh2U25kalpGTTFNbXhXWlhwaU4xWXZPVlJ0UjNWbWFFMUJha0poYWtSMVlVazJSMUJsU0ZWTU1IZEZhbVZ3ZEROUlRqTlJaRVZhWVFwVFowTndZbWhEZEZsNlNrOHdTelUxY3pCU2VqUlhOR05GTlRaelpuVnJLelo1UVQwS0xTMHRMUzFGVGtRZ1EwVlNWRWxHU1VOQlZFVXRMUzB0TFFvPSJ9fX19","integratedTime":1678730267,"logIndex":15338969,"logID":"c0d23d6ad406973f9559f3ba2d1ca01f84147d8ffc5b8445c224f98b9591801d"}},"Issuer":"https://accounts.google.com","Subject":"keyless@distroless.iam.gserviceaccount.com"}}]
```

**Actual Result**
```
#!/bin/bash -eo pipefail
cosign dockerfile verify --insecure-ignore-tlog=true --base-image-only --certificate-identity keyless@distroless.iam.gserviceaccount.com --certificate-oidc-issuer https://accounts.google.com ./Dockerfile

Extracted image(s): gcr.io/distroless/python3-debian11:nonroot
Error: loading public key: open ****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************: file name too long
main.go:74: error during command execution: loading public key: open ****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************: file name too long

Exited with code exit status 1
CircleCI received exit code 1
```

**Version**

2.0.0
