### ISSUE TITLE
Environment variable ID token detection

### ISSUE THREAD

**Issue by wlynch** [sigstore/cosign#2863]
**Description**

I'd like to propose adding environment variable OIDC token detection for cosign.

Main use case is to support [GitLab CI OIDC tokens](https://docs.gitlab.com/ee/ci/secrets/id_token_authentication.html) - see https://github.com/sigstore/fulcio/pull/983 for more details.

## Proposal

Today, users can already use arbitrary OIDC tokens by using the `--identity-token` flag.

```sh
cosign sign --identity-token=${TOKEN} ...
```

To make this easier, I want to allow cosign to detect a token from environment variables.
To help avoid collisions with existing token variables, we should use a prefixed value such as `SIGSTORE_ID_TOKEN`.

This could also be used to allow other CI providers to hook in without needing additional changes to cosign (though I'm still in support for allowing custom providers per host).

Example: GitLab

```
build:
  stage: build
  id_tokens:
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
     - cosign sign registry.gitlab.com/my-image
```

I'm happy to implement this.

Previous GitLab related issues:
- https://github.com/sigstore/cosign/issues/2697
- https://github.com/sigstore/cosign/issues/1254
