### ISSUE TITLE
Please support group variables on GitLab

### ISSUE THREAD

**Issue by jas4711** [sigstore/cosign#2914]
Hi.  Using `cosign generate-key-pair gitlab://foo/bar` works fine if the destination is a project, but it seems useful to also generate keys and set the variables for a group, so the variables are reachable for all sub-groups.

Compare this successful run:

```
jas@kaka:~$ cosign generate-key-pair gitlab://debdistutils/canary/trisquel
Enter password for private key: 
jas@kaka:~$ 
```

With the following failing run:

```
jas@kaka:~$ cosign generate-key-pair gitlab://debdistutils/canary
Enter password for private key: 
Enter password for private key again: 
WARNING: If you are using a self-hosted gitlab please set the "GITLAB_HOST" your server name.
Error: could not create "COSIGN_PASSWORD" variable: POST https://gitlab.com/api/v4/projects/debdistutils/canary/variables: 404 {message: 404 Project Not Found}
main.go:74: error during command execution: could not create "COSIGN_PASSWORD" variable: POST https://gitlab.com/api/v4/projects/debdistutils/canary/variables: 404 {message: 404 Project Not Found}
jas@kaka:~$ 
```

I would want the second command to populate variables for that sub-group.

Thank you!

**Comment by rnjudge** [comment]
@znewman01 is this something I could work on? 

Additionally, is this only for gitlab or should this apply to github key pairs as well?

**Comment by znewman01** [comment]
That would be great @rnjudge ! Thanks 🙂 

> Additionally, is this only for gitlab or should this apply to github key pairs as well?

Good call. I think the analog in GitHub would be *organization* secrets. That seems useful to me!

**Comment by cpanato** [comment]
+1 on the organization secrets for github, but i think this will be another PR

**Comment by vishal-chdhry** [comment]
Hi @rnjudge! May I give this a try if you are not working on this anymore?

**Comment by robertohueso** [comment]
Hi :smile: It's been some time since the last comment on this issue, I'll work on this

**Comment by remkolems** [comment]
@robertohueso Thanks for doing this. This is follow-up and FYI.

As of this moment I'm testing out cosign within a gitlab-ci pipeline. 

I initially created project level COSIGN variables within GitLab on a self-hosted instance. Worked out great. 

As more projects came along for signing container images, I copied those same variables as a test use case to the main group and deleted the project level variables. Within GitLab those main group cosign variables are now `inherited` to all projects and/or subgroups. 

But using 'cosign sign -y --key gitlab://${PROJECTID} "$IMAGE_W_DIGEST"' within the pipeline of project within a subgroup - inherited group variables are visible - cosign returns the following error: 

```log
# 324 is the project id. Test done with group id, also same error.
Error: signing [reg.<own-domain>.com/library/dnsmasq@sha256:34b9a5c7321cfcd1d1e1111049ee15916b7bb2d1de7d840aeebc060bcf1796a9]: getting signer: reading key: could not retrieve "COSIGN_PUBLIC_KEY" variable: GET https://git.<own-domain>.com/api/v4/projects/324/variables/COSIGN_PRIVATE_KEY: 404 {message: 404 Variable Not Found}
```

```yaml
 # part of pipeline job
   before_script:
    # https://docs.sigstore.dev/cosign/system_config/installation/#alpine-linux
    - apk add --no-cache --update cosign grep jq # cosign slightly outdated but cleaner code
  script:
    - export COSIGN_PASSWORD=${COSIGN_PASSWORD}
    - export GITLAB_TOKEN=${COSIGN_PAT}
    - export GITLAB_HOST=${CI_API_V4_URL}
    #
    # https://github.com/sigstore/cosign/issues/2914 "Please support group variables on GitLab"
    #
    - |
      cosign sign -y --key gitlab://${PROJECTID} "$IMAGE_W_DIGEST" \
        --annotations "com.gitlab.ci.project.name=$CI_PROJECT_NAME" \
        --annotations "tag=$IMAGE_TAG"
```

![image](https://github.com/user-attachments/assets/332be4bb-ded6-43f7-aa0e-83997aa42252)
