### ISSUE TITLE
Bug: Using cosign in gh actions with Azure KMS (KeyVault)  - Failed to refresh the Token: invalid_request

### ISSUE THREAD

**Issue by hegerdes** [sigstore/cosign#2999]
**Description**
Im getting an authentication error using cosign in GH actions with Azure KeyVault:
```bash
cosign sign --key  azurekms://MyKeyVault.vault.azure.net/MyKeyName myimage@digest
Error: public key: public key: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://***.vault.azure.net/keys/MyKeyName/?api-version=7.1: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
main.go:74: error during command execution: public key: public key: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://***.vault.azure.net/keys/MyKeyName/?api-version=7.1: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
```
The azure login works and I can also read the key via the az cli but it crashes when I use cosign.
Locally it is working without a problem. My workflow is this:
```yml
name: Docker-Build
on:
  push:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.MY_DOCKERHUB_USER }}
          password: ${{ secrets.MY_DOCKERHUB_TOKEN }}

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          sbom: true
          tags: ${{ github.actor }}/myimage:${{ matrix.app }}-${{ github.ref_name }}

      - name: Sign the published Docker image
        run: |
          # Works
          az keyvault key list --id {{ secrets.COSIGN_KEY_STORE }}
          # Does not work
          cosign sign --key ${{ secrets.COSIGN_KEY_STORE }} ${{ github.actor }}/myimage@${{ steps.build-and-push.outputs.digest }}

```

**Version**
```
  ______   ______        _______. __    _______ .__   __.
 /      | /  __  \      /       ||  |  /  _____||  \ |  |
|  ,----'|  |  |  |    |   (----`|  | |  |  __  |   \|  |
|  |     |  |  |  |     \   \    |  | |  | |_ | |  . `  |
|  `----.|  `--'  | .----)   |   |  | |  |__| | |  |\   |
 \______| \______/  |_______/    |__|  \______| |__| \__|
cosign: A tool for Container Signing, Verification and Storage in an OCI registry.

GitVersion:    v2.0.2
GitCommit:     871448050b924a7946ebe47678f23aae09ef432d
GitTreeState:  clean
BuildDate:     2023-04-24T17:31:42Z
GoVersion:     go1.20.3
Compiler:      gc
Platform:      linux/amd64
```

**Comment by hegerdes** [comment]
I really dug deep into it but had no luck at first. I found this:  [cosign-docs](https://devblogs.microsoft.com/azure-sdk/authentication-and-the-azure-sdk/#environment-variables) but I really wanted to use the password-less setup with Federated Identity Credentials via the AZ-CLI.
While look at [sigstore/sigstore/blob/pkg/signature/kms/azure/client.go](https://github.com/sigstore/sigstore/blob/1d364091f84230e251d425313e87b8cdd78a971f/pkg/signature/kms/azure/client.go#LL141C27-L141C44) I found that cosign does indeed support AZ-CLI login but in order for that to work you have to set the env  `AZURE_AUTH_METHOD=cli` and this works.

So use:
```yml
      - name: Sign the published Docker image
        env:
          AZURE_AUTH_METHOD: cli
        run: |
          # Works
          az keyvault key list --id {{ secrets.COSIGN_KEY_STORE }}
          # Does not work
          cosign sign --key ${{ secrets.COSIGN_KEY_STORE }} ${{ github.actor }}/myimage@${{ steps.build-and-push.outputs.digest }}
```
