### ISSUE TITLE
Cosign 2.2.1 Docker image missing /bin/sh

### ISSUE THREAD

**Issue by Fredouye** [sigstore/cosign#3361]
**Description**

Cosign 2.2.1 does not include the `sh` executable, and fails to run through a GitLab CI pipeline.

Extract of `.gitlab-ci.yml` : 

```yaml
sign-image:
  stage: push
  variables:
    SSL_CERT_FILE: ${VAULT_CACERT}
  image:
    name: gcr.io/projectsigstore/cosign:v2.2.1
    entrypoint: [""]
  script:
    - cosign login ${REGISTRY_URL} --username ${REGISTRY_USERNAME} --password ${REGISTRY_PASSWORD}
    - echo $COSIGN_PRIVATE_KEY | base64 -d > /tmp/cosign_private_key
    - cosign sign --key /tmp/cosign_private_key "${REGISTRY_URL}/${REGISTRY_PROJECT}/${IMAGE}:${VERSION}" --yes
    - rm /tmp/cosign_private_key -f
```

Result :

```yaml
Using docker image sha256:aadc646735691b2cec958e1930c2b815f66f6b4aec58d4dc88e1211dd463083b for gcr.io/projectsigstore/cosign:v2.2.1 with digest gcr.io/projectsigstore/cosign@sha256:88498ed17e61605cd68a5fc9d1fcd756ae0ef2d5515417881d739654accf818f ...
Cleaning up project directory and file based variables 00:02
ERROR: Job failed (system failure): Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "sh": executable file not found in $PATH: unknown (exec.go:78:2s)
```

Downgrading to Cosign 2.2.0 fixes the issue.

By the way, Cosign 2.2.1 Docker image is much smaller than 2.2.0 (107 Mb instead of 124 Mb).

**Version**

Cosign 2.2.1 Docker image (`gcr.io/projectsigstore/cosign:v2.2.1`).

**Comment by haydentherapper** [comment]
This was intentional, we switched to a newer distroless base image without a shell. I’m open to adding it back, but I believe this could be refactored to not need a shell.  

Thoughts @cpanato @hectorj2f?

**Comment by Fredouye** [comment]
It seems a shell [is needed](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#override-the-entrypoint-of-an-image) to run Cosign from a GitLab CI pipeline.

For the same reason, I use the `debug` image for [Kaniko](https://github.com/GoogleContainerTools/kaniko/blob/main/README.md#debug-image) :

```
The kaniko executor image is based on scratch and doesn't contain a shell. We provide gcr.io/kaniko-project/executor:debug, a debug image which consists of the kaniko executor image along with a busybox shell to enter.
```

**Comment by hectorj2f** [comment]
@Fredouye You could use `cgr.dev/chainguard/cosign:latest-dev` which includes a shell. Obviously I'd advocate to use `cgr.dev/chainguard/cosign:latest` but you can use the `latest-dev` image tag which is an explicit extension of the original image which includes `git, bash, and other packages.

**Comment by haydentherapper** [comment]
@Fredouye I'll take a look at creating a `dev` or `debug` image. I'm not familiar with GitLab CI, but from the example you've given, it seems like a shell is necessary. Maybe there's a way to do a multi-step process where the key and registry credentials are obtained and passed to Cosign invocation step?

**Comment by hectorj2f** [comment]
Yes, @haydentherapper is right! You should be able to run it in a multi-step process as an alternative solution. 

Also there is a typo in your script `cosign login`.

**Comment by haydentherapper** [comment]
@imjasonh, is it possible to create two containers using ko where all configuration but the base images are different, while also controlling the name of the container?

Concretely, I would like the following config to work, but I don't think it does, because I can't specify the same `main` path twice, _I think_.

```
defaultBaseImage: gcr.io/distroless/static-debian12:nonroot
baseImageOverrides:
   <path-to-cosign-debug>: gcr.io/distroless/static-debian12:debug-nonroot

builds:
- id: cosign
  dir: .
  main: ./cmd/cosign
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  - -tags
  - "{{ .Env.GIT_HASH }}"
  - -tags
  - "{{ .Env.GIT_VERSION }}"
  ldflags:
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"

builds:
- id: cosign-debug
  dir: .
  main: ./cmd/cosign
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  - -tags
  - "{{ .Env.GIT_HASH }}"
  - -tags
  - "{{ .Env.GIT_VERSION }}"
  ldflags:
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"
```
