### ISSUE TITLE
[cosign sign] UNAUTHORIZED: You don't have the needed permissions

### ISSUE THREAD

**Issue by rawlingsj** [sigstore/cosign#337]
Hi, just been looking at signing all Jenkins X images and would also like to make it super easy for Jenkins X users to get automated signing in their own pipelines.  We're using a Tekton task + secret that contains the private key + cosign password like this...

```yaml
apiVersion: v1
stringData:
  cosign.key: |-
    -----BEGIN ENCRYPTED COSIGN PRIVATE KEY-----
    abc123....
    -----END ENCRYPTED COSIGN PRIVATE KEY-----
  password: foo
kind: Secret
metadata:
  name: cosign
type: Opaque
```
When the `cosign sign` step runs we're hitting `UNAUTHORIZED: You don't have the needed permissions` when pushing the signature.  We tend to have a mix of container registries that we push to and we use a `~/.docker/config.json` for auth to these registries.  

I managed to work around the error above by adding `docker-credential-gcr` to the cosign step image like this https://github.com/rawlingsj/jx3-pipeline-catalog/blob/de0d1aff086f90f22da15835b7e0c1498ee59b3e/tasks/cosign/cosign.yaml#L19-L21 - using this workaround we do get signing of the images, it seems to work great.

AFAIK Kaniko uses a similar approach here https://github.com/GoogleContainerTools/kaniko/blob/7b6495426d9a4713b997a1afcf197d87eecb33a3/deploy/Dockerfile_debug#L32-L45 but I wasn't sure if this is how you'd expect folks to auth with registries?  

Should these credential helper CLIs be added to the cosign images or is there a better / preferred way?
