### ISSUE TITLE
Idea: kubectl plugin to embed signatures in objects

### ISSUE THREAD

**Issue by dlorenc** [SigStore/cosign#38]
This could work something like:

```
1. Go through a k8s object looking for images
2. For each image, pull do something like "cosign verify" and get all verified payloads
3. Attach those payloads directly into the k8s object as annotations
```

This way deployment time policy enforcement (OPA, etc.) could look directly at the yaml rather than needing to interact with an external service.

**Comment by danmx** [comment]
Afaik, `kubectl apply` doesn't support plugins so this could work for pre-enforcement phase, scan and annotate existing workloads.

Creating a [`kustomize` plugin](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/) would help during deployment time.

**Comment by joshes** [comment]
I've been thinking about this and yes, as @danmx says we can't run this at `apply` time and not everyone utilizes `kustomize` templating so would limit the usage I think.

What about a discrete plugin that performs 2 actions?

1. **kubectl cosign-update** Updates the resource(s) (writes) with relevant validation metadata on each kind containing an image
2. **kubectl cosign-validate** Validates all kinds containing an image and validation metadata

The upswing is it could be version controlled, I'm personally not a fan of the idea of changing resources enroute the cluster.

As for example payload:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosign-test-deployment
  labels:
    app: cosign-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cosign-test
  template:
    metadata:
      labels:
        app: cosign-test
      cosign:
        containers:
          - joshes/cosign-test:
              identity:
                docker-reference: index.docker.io/joshes/cosign-test
              image:
                docker-manifest-digest: sha256:94ff46afc672bf4750b837e2819b86c8c8335bd0f3e233c86b3af6a180d09f26
              optional:
                - test: true
                - hello: world
                - validated: 2021-07-25T16:39:41.034Z
    spec:
      containers:
      - name: joshes/cosign-test
        image: joshes/cosign-test:latest
        ports:
        - containerPort: 80
```

And the OPA would look something like the following for this use-case (roughly)

```
package kubernetes.admission

deny[msg] {
  # Other types to be supported of course, just an example
  input.request.kind.kind == "Deployment"
  validation := input.request.object.spec.template.metadata.cosign.containers[_]
  # TODO check validation is present, contains type and/or confirm digest exists in registry
  msg := sprintf("image '%v' not validated or failed validation. only verified images can run on this cluster", [image])
}
```

This all leads me to wonder though; there's nothing stopping this same principle being applied to the _resources themselves_. If we signed the resource _and images_ we could enforce true identity on the entire payload from the top down.

Wouldn't mind taking a swing at this once the requirements are firmed up though.
