### ISSUE TITLE
cosigned: create a CRD to declare signed image policies per cluster

### ISSUE THREAD

**Issue by hectorj2f** [sigstore/cosign#594]
**Description**

The idea is to create a cluster-scoped CR to specify a signed image policy on their kubernetes cluster. This policy can be configured to verify signed images from specified patterns.

Based on our implementation of a similar admission controller, we expose a CR with several fields:

`publicKeys`: defines the list of valid public keys.
`registries`: defines the link between registries and defined keys where to apply these rules.
`unmatchedImagePolicy`:  specifies the behavior of the admission controller (Allow|Deny) whenever the policy is satisfied or not.

An example of a Policy:

```
kind: ClusterImagePolicy
metadata:
 name: image-policy
spec:
 unmatchedImagePolicy: <Allow/Deny>
 publicKeys:
 - name: cosign-key-1
   publicKey: <public-key>
 registries:
 - pattern: my.registry.org/library/*
   keys:
   - name: cosign-key-1
  ```

I cc @stormqueen1990 and @kkavitha @elfotografo007 as creators of this approach. So they can chime in here.
