### ISSUE TITLE
Should be worrying about ephemeral containers

### ISSUE THREAD

**Issue by vaikas** [sigstore/cosign#820]
**Question**
While I was looking at the #809 thought about how we might want to handle ephemeral containers. Just wanted to jot this down and see what folks thought about this. Seems like something to at least think about.

https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/

**Comment by developer-guy** [comment]
hello @vaikas, this is an interesting case nice !! I found this, it might be useful for us: 
👉 https://github.com/kubernetes/kubernetes/issues/92557

**Comment by dlorenc** [comment]
Yes!

**Comment by developer-guy** [comment]
Hello, kindly ping here 🙋🏻‍♂️ We can use ephemeral containers sub resource definition in the rules section of Validating/MutatingWebhookConfiguration as follows 👇
```
rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - pods/ephemeralcontainers
```
