### ISSUE TITLE
support generating Tekton Task & TaskRun

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign#947]
**Description**

Wouldn't be nice if we can support generating `Tekton Task & TaskRun` resources via new command? This command will do two things. The first one is generating key pairs using the `k8s://` scheme and creating necessary **Task** & **TaskRun** resources.

<details>

<summary> Sample Cosign Tekton Task </summary>

```YAML
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosign
  labels:
    app.kubernetes.io/version: "0.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
spec:
  description: >-
    These tasks make it possible to use cosign within your Tekton pipelines

    cosign is a tool for signing and verifying software artifacts.

  workspaces:
  - name: source
  params:
  - name: command
    type: string
  - name: image
    type: string
  results:
    - name: email
      description: The email from the certificate common name in JSON format
  steps:
  - name: cosign
    workingDir: $(workspaces.source.path)
    image: gcr.io/projectsigstore/cosign/ci/cosign:v0.5.0
    env:
      - name: COSIGN_PUBLIC_KEY
        valueFrom:
          secretKeyRef:
            name: signing-secrets
            key: cosign.pub   
    script: |
      #!/busybox/env /busybox/sh
      echo "${COSIGN_PUBLIC_KEY}" >> cosign.pub
      echo "GK: Verify using the public key:"
      cat cosign.pub
      CMD="cosign $(params.command) -key cosign.pub $(params.image)"
      echo "${CMD}"
      ERR_MSG="Failed to $(params.command) $(params.image)"
      ${CMD} &> result
      err=$?
      cat result
      if [[ ${err} -ne 0 ]]; then
        echo "${ERR_MSG}"
        exit 1
      fi
```

</details>

> Credit: https://github.com/ztsc/tekton

cc: @Dentrax @erkanzileli @gkovan
